from datetime import datetime

USERS_20_SEED = [
    # --- 8 FARMERS ---
    {
        "id": "f0000000-0000-0000-0000-000000000001",
        "name": "Ramesh Patel",
        "phone": "9876543210",
        "email": "ramesh.patel@farmnex.in",
        "role": "farmer",
        "language_pref": "hi",
        "verified": True,
        "farmer_profile": {
            "location": "Indore, Madhya Pradesh",
            "lat": 22.7196,
            "lng": 75.8577,
            "fpo_name": "Malwa Kisan Samriddhi FPO",
        },
        "crops": ["Soybean", "Wheat", "Gram"],
        "farm_size": 18,
        "soil": "Deep Black Vertisol",
        "about": "Growing certified JS-9560 Soybean and Sharbati Wheat across 18 acres in Sanwer. Geotagged farm gate with digital moisture testing facility.",
        "headline": "Soybean & Sharbati Wheat Specialist | Sanwer, Indore"
    },
    {
        "id": "f0000000-0000-0000-0000-000000000002",
        "name": "Devendra Mandloi",
        "phone": "9826112233",
        "email": "devendra.mandloi@farmnex.in",
        "role": "farmer",
        "language_pref": "hi",
        "verified": True,
        "farmer_profile": {
            "location": "Khargone, Madhya Pradesh",
            "lat": 21.8234,
            "lng": 75.6179,
            "fpo_name": "Nimar Cotton & Chilli Producer Co",
        },
        "crops": ["Cotton", "Soybean", "Chilli"],
        "farm_size": 24,
        "soil": "Nimar Alluvial Loam",
        "about": "Cultivating long-staple DCH-32 Bt Cotton and Teja Red Chilli with micro-drip fertigation in Kasrawad tehsil. Consistent 29mm staple length.",
        "headline": "Long-Staple Cotton & Teja Chilli Grower | Khargone"
    },
    {
        "id": "f0000000-0000-0000-0000-000000000003",
        "name": "Sunita Verma",
        "phone": "9893223344",
        "email": "sunita.verma@farmnex.in",
        "role": "farmer",
        "language_pref": "hi",
        "verified": True,
        "farmer_profile": {
            "location": "Dewas, Madhya Pradesh",
            "lat": 22.9676,
            "lng": 76.0534,
            "fpo_name": "Chamunda Mahila Kisan Producer Co",
        },
        "crops": ["Soybean", "Garlic", "Gram"],
        "farm_size": 15,
        "soil": "Medium Black Soil",
        "about": "Leading organic certified woman farmer cultivating Amleta white garlic and high-protein soybean. Focus on zero chemical residue produce.",
        "headline": "Progressive Organic Farmer & Garlic Specialist | Dewas"
    },
    {
        "id": "f0000000-0000-0000-0000-000000000004",
        "name": "Rajesh Pawar",
        "phone": "9425099881",
        "email": "rajesh.pawar@farmnex.in",
        "role": "farmer",
        "language_pref": "hi",
        "verified": True,
        "farmer_profile": {
            "location": "Sehore, Madhya Pradesh",
            "lat": 23.2032,
            "lng": 77.0844,
            "fpo_name": "Sehore Agritech Kisan FPC",
        },
        "crops": ["Desi Gram", "Wheat", "Mustard"],
        "farm_size": 12,
        "soil": "Clay Loam",
        "about": "Specializing in JG-11 Desi Gram (Chana) and Lokwan wheat. All harvesting handled with modern pneumatic threshers for minimum broken grains.",
        "headline": "Desi Gram & Lokwan Wheat Grower | Sehore"
    },
    {
        "id": "f0000000-0000-0000-0000-000000000005",
        "name": "Mukesh Choudhary",
        "phone": "9827334455",
        "email": "mukesh.choudhary@farmnex.in",
        "role": "farmer",
        "language_pref": "hi",
        "verified": True,
        "farmer_profile": {
            "location": "Ujjain, Madhya Pradesh",
            "lat": 23.1765,
            "lng": 75.7885,
            "fpo_name": "Mahakal Krishi Producer Co",
        },
        "crops": ["Soybean", "Onion", "Potato"],
        "farm_size": 20,
        "soil": "Rich Black Cotton",
        "about": "Operating solar-powered cold storage aggregation for Nashik Red onion varieties and certified seed-grade soybean lots in Tarana tehsil.",
        "headline": "Onion & Seed-Grade Soybean Cultivator | Ujjain"
    },
    {
        "id": "f0000000-0000-0000-0000-000000000006",
        "name": "Vikram Singh Solanki",
        "phone": "9829445566",
        "email": "vikram.solanki@farmnex.in",
        "role": "farmer",
        "language_pref": "hi",
        "verified": True,
        "farmer_profile": {
            "location": "Kota, Rajasthan",
            "lat": 25.2138,
            "lng": 75.8648,
            "fpo_name": "Chambal Valley Kisan FPC",
        },
        "crops": ["Mustard", "Soybean", "Paddy"],
        "farm_size": 28,
        "soil": "Canal Irrigated Loam",
        "about": "Farming high-oil Pusa Mustard (41.8% oil yield) and 1509 Basmati paddy along the Chambal river canal belt. Prompt mechanized bagging.",
        "headline": "Pusa Mustard & Basmati Producer | Kota, Rajasthan"
    },
    {
        "id": "f0000000-0000-0000-0000-000000000007",
        "name": "Balram Patidar",
        "phone": "9425112299",
        "email": "balram.patidar@farmnex.in",
        "role": "farmer",
        "language_pref": "hi",
        "verified": True,
        "farmer_profile": {
            "location": "Mandsaur, Madhya Pradesh",
            "lat": 24.0722,
            "lng": 75.0689,
            "fpo_name": "Malwa Spices Producer Co",
        },
        "crops": ["Garlic", "Coriander", "Soybean"],
        "farm_size": 16,
        "soil": "Rich Sandy Loam",
        "about": "Export quality G2 Garlic and Eagle variety green Coriander cultivator in Mandsaur mandi hub. Naturally shade cured and graded.",
        "headline": "Export Quality Garlic & Coriander Grower | Mandsaur"
    },
    {
        "id": "f0000000-0000-0000-0000-000000000008",
        "name": "Anil Dhangar",
        "phone": "9755667788",
        "email": "anil.dhangar@farmnex.in",
        "role": "farmer",
        "language_pref": "hi",
        "verified": True,
        "farmer_profile": {
            "location": "Harda, Madhya Pradesh",
            "lat": 22.3444,
            "lng": 77.0982,
            "fpo_name": "Narmada Valley Farmers Producer Co",
        },
        "crops": ["Moong", "Soybean", "Wheat"],
        "farm_size": 32,
        "soil": "Narmada Basin Alluvial",
        "about": "Pioneer in triple-cropping rotation: Summer Moong (green gram), Kharif Soybean, and Rabi Sharbati Wheat. 100% canal drip irrigated.",
        "headline": "Summer Moong & High-Yield Soybean Cultivator | Harda"
    },

    # --- 4 FARMER PRODUCER ORGANIZATIONS (FPOs) ---
    {
        "id": "fpo00000-0000-0000-0000-000000000001",
        "name": "Malwa Kisan Samriddhi FPO",
        "phone": "9826155001",
        "email": "contact@malwakisanfpo.org",
        "role": "fpo",
        "language_pref": "hi",
        "verified": True,
        "fpo_profile": {
            "organization_name": "Malwa Kisan Samriddhi FPO",
            "district": "Indore",
            "member_count": 340,
        },
        "crops": ["Soybean", "Wheat", "Gram", "Onion"],
        "about": "Registered under Companies Act with 340 smallholder farmers. Operating 2 central aggregation hubs in Rau & Sanwer with electronic weighbridges and moisture testing labs.",
        "headline": "340-Member Aggregation Cooperative | Rau & Sanwer Hubs"
    },
    {
        "id": "fpo00000-0000-0000-0000-000000000002",
        "name": "Narmada Valley Farmers Producer Co",
        "phone": "9826330011",
        "email": "procurement@narmadafpc.org",
        "role": "fpo",
        "language_pref": "hi",
        "verified": True,
        "fpo_profile": {
            "organization_name": "Narmada Valley Farmers Producer Co",
            "district": "Harda",
            "member_count": 520,
        },
        "crops": ["Moong", "Soybean", "Kodo Millet", "Wheat"],
        "about": "SFAC & NABARD partner FPC with 520 smallholders. Operates direct procurement contracts with national solvent plants and institutional millers.",
        "headline": "NABARD Partner Collective | 520 Farmers | Harda & Hoshangabad"
    },
    {
        "id": "fpo00000-0000-0000-0000-000000000003",
        "name": "Chamunda Mahila Kisan FPC",
        "phone": "9425177880",
        "email": "trade@chamundafpc.in",
        "role": "fpo",
        "language_pref": "hi",
        "verified": True,
        "fpo_profile": {
            "organization_name": "Chamunda Mahila Kisan FPC",
            "district": "Dewas",
            "member_count": 280,
        },
        "crops": ["Garlic", "Soybean", "Gram"],
        "about": "100% women-led farmer producer company in Sonkatch tehsil. Specializing in graded garlic bulbs, cold-pressed artisanal mustard oil, and organic soybean lots.",
        "headline": "All-Women Farmer Producer Co | 280 Members | Sonkatch, Dewas"
    },
    {
        "id": "fpo00000-0000-0000-0000-000000000004",
        "name": "Sehore Agritech Kisan Collective",
        "phone": "9893441122",
        "email": "operations@sehorekisan.org",
        "role": "fpo",
        "language_pref": "hi",
        "verified": True,
        "fpo_profile": {
            "organization_name": "Sehore Agritech Kisan Collective",
            "district": "Sehore",
            "member_count": 410,
        },
        "crops": ["Desi Gram", "Lokwan Wheat", "Mustard"],
        "about": "410 certified pulse cultivators. Centralized cleaning, optical sorting, and digital assay documentation ensuring zero impurity lots for wholesale processors.",
        "headline": "Pulse Sorting & Grading Collective | 410 Members | Sehore"
    },

    # --- 5 COMMERCIAL PROCESSORS & BULK BUYERS ---
    {
        "id": "b0000000-0000-0000-0000-000000000001",
        "name": "Anita Sharma (Agrocorp)",
        "phone": "9811111111",
        "email": "buyer1@agrocorp.in",
        "role": "buyer",
        "language_pref": "en",
        "verified": True,
        "buyer_profile": {
            "business_name": "Agrocorp Central Processing Pvt Ltd",
            "gst_verified": True,
            "location": "Dewas Industrial Area, Madhya Pradesh",
            "lat": 22.9676,
            "lng": 76.0534,
        },
        "crops": ["Soybean", "Mustard"],
        "about": "Integrated 1,200 MT/day solvent extraction and edible oil refinery in Dewas. Direct procurement contracts with verified FPOs and farmers with 24-hour escrow release.",
        "headline": "Procurement Head · Agrocorp Central Processing Pvt Ltd"
    },
    {
        "id": "b0000000-0000-0000-0000-000000000002",
        "name": "Vikram Singh (Bhopal Solvex)",
        "phone": "9822222222",
        "email": "procurement@bhopalsolvex.com",
        "role": "buyer",
        "language_pref": "en",
        "verified": True,
        "buyer_profile": {
            "business_name": "Bhopal Solvex & Oils Ltd",
            "gst_verified": True,
            "location": "Mandideep Industrial Estate, Bhopal, MP",
            "lat": 23.0722,
            "lng": 77.5255,
        },
        "crops": ["Soybean", "Mustard", "Cottonseed"],
        "about": "Specialized solvent processing & de-oiled cake (DOC) exporter to Southeast Asia. Sourcing 35,000 MT seasonally with direct weighbridge and gate receipt assay.",
        "headline": "Director of Sourcing · Bhopal Solvex & Oils Ltd"
    },
    {
        "id": "b0000000-0000-0000-0000-000000000003",
        "name": "Suresh Singhal (Mahakal Feeds)",
        "phone": "9833333333",
        "email": "trade@mahakalfeeds.com",
        "role": "buyer",
        "language_pref": "hi",
        "verified": True,
        "buyer_profile": {
            "business_name": "Mahakal Feeds & Grain Mandi Hub",
            "gst_verified": True,
            "location": "Ujjain Grain Market, Madhya Pradesh",
            "lat": 23.1765,
            "lng": 75.7885,
        },
        "crops": ["Maize", "Soybean", "Gram"],
        "about": "Commercial poultry and cattle compound feed manufacturing plant in Ujjain. Continuous procurement of high-protein coarse grains and broken pulses.",
        "headline": "Chief Commercial Officer · Mahakal Feeds & Grain Hub"
    },
    {
        "id": "b0000000-0000-0000-0000-000000000004",
        "name": "Kailash Agarwal (Malwa Flour)",
        "phone": "9826019922",
        "email": "procurement@malwaflour.in",
        "role": "buyer",
        "language_pref": "hi",
        "verified": True,
        "buyer_profile": {
            "business_name": "Malwa Roller Flour Mills Ltd",
            "gst_verified": True,
            "location": "Pithampur Sector 3, Dhar, MP",
            "lat": 22.6139,
            "lng": 75.6822,
        },
        "crops": ["Wheat", "Gram"],
        "about": "Industrial flour milling capacity of 800 MT/day producing Chakki Atta, Maida, and Suji for national FMCG packaging. Premium rates for Sharbati & Lokwan varieties.",
        "headline": "Managing Director · Malwa Roller Flour Mills Ltd"
    },
    {
        "id": "b0000000-0000-0000-0000-000000000005",
        "name": "Rajiv Mehra (Deccan Spices)",
        "phone": "9823118800",
        "email": "sourcing@deccanspices.com",
        "role": "buyer",
        "language_pref": "en",
        "verified": True,
        "buyer_profile": {
            "business_name": "Deccan Spice & Commodity Exporters",
            "gst_verified": True,
            "location": "Neemuch Mandi Hub, Madhya Pradesh",
            "lat": 24.4739,
            "lng": 74.8703,
        },
        "crops": ["Garlic", "Coriander", "Mustard", "Chilli"],
        "about": "APEDA certified spice processor exporting dehydrated garlic flakes, whole coriander, and organic mustard seeds to Middle East & Europe.",
        "headline": "Head of Agri-Sourcing · Deccan Spice Exporters"
    },

    # --- 2 CERTIFIED AGRONOMY & MANDI ASSAY EXPERTS ---
    {
        "id": "exp00000-0000-0000-0000-000000000001",
        "name": "Dr. Kavita Rao",
        "phone": "9826778811",
        "email": "kavita.agronomy@farmnex.demo",
        "role": "expert",
        "language_pref": "en",
        "verified": True,
        "crops": ["Soybean", "Wheat", "Mustard"],
        "about": "Ph.D. in Agronomy with 16 years advising central Indian farmers on oilseed quality, post-harvest drying protocols, pest mitigation, and mandi assay compliance.",
        "headline": "Senior Agronomist & Mandi Quality Consultant | ICAR Advisor"
    },
    {
        "id": "exp00000-0000-0000-0000-000000000002",
        "name": "Dr. B. L. Meena",
        "phone": "9414002233",
        "email": "bl.meena@soilscience.org",
        "role": "expert",
        "language_pref": "hi",
        "verified": True,
        "crops": ["Cotton", "Gram", "Garlic"],
        "about": "Principal Scientist (Soil Health & Micro-Nutrients). Specialist in vertisol black soil salinity rectification, organic compost balancing, and export pesticide residue assays.",
        "headline": "Principal Soil Scientist & Post-Harvest Assay Specialist"
    },

    # --- 2 DIRECT CONSUMERS / RETAIL BUYERS ---
    {
        "id": "con00000-0000-0000-0000-000000000001",
        "name": "Meera Joshi",
        "phone": "9827001122",
        "email": "meera@farmnex.demo",
        "role": "consumer",
        "language_pref": "en",
        "verified": True,
        "consumer_profile": {
            "interests": ["traceable produce", "cold-pressed oils", "millets", "stone-ground flour"],
        },
        "crops": ["Cold-pressed oils", "Millets", "Sharbati Atta"],
        "about": "Home cook and supporter of sustainable direct farm-to-table produce. Buys single-origin cold-pressed oils and unpolished pulses directly from FPOs.",
        "headline": "Traceable Agri Advocate & Direct Consumer | Indore"
    },
    {
        "id": "con00000-0000-0000-0000-000000000002",
        "name": "Aakash Kulkarni",
        "phone": "9881223344",
        "email": "aakash.kulkarni@urbanorganics.in",
        "role": "consumer",
        "language_pref": "en",
        "verified": True,
        "consumer_profile": {
            "interests": ["organic produce", "residue-free spices", "traditional grains"],
        },
        "crops": ["Kodo Millet", "Desi Toor Dal", "Wood-Pressed Oil"],
        "about": "Community kitchen coordinator procuring certified residue-free farm grains and pure wood-pressed soybean oil in bulk for community distribution.",
        "headline": "Urban Community Kitchen Organizer | Pune & Indore"
    },

    # --- 1 PLATFORM OPERATIONS ADMIN ---
    {
        "id": "a0000000-0000-0000-0000-000000000001",
        "name": "FarmNex Operations Admin",
        "phone": "9999999999",
        "email": "admin@farmnex.in",
        "role": "admin",
        "language_pref": "en",
        "verified": True,
        "crops": ["All Commodities"],
        "about": "Farm-Nex central operations, dispute resolution desk, weighing compliance monitor, and escrow settlement overseer.",
        "headline": "Central Operations & Mandi Settlement Desk"
    }
]
